Update compilerun

diff --git a/compilerun b/compilerun
--- a/compilerun
+++ b/compilerun
@@ -3,9 +3,9 @@ cd src
 ls -d */ | while read i; do (
     cd "$i"
     echo "Running $i"
-    dos2unix compile.bat run.bat
-    command=$(cat compile.bat) eval 'bash -c "${command//;/:}"' 2>&1 || { echo "Compile failed $i"; exit; }
-    command=$(cat run.bat) eval 'bash -c "${command//;/:}"' 2>&1 || echo "Run failed $i"
+    dos2unix compile.bat run.bat > /dev/null 2>&1 
+    sed -e 's/;/:/g' -e 's/\\/\//g' compile.bat | bash 2>&1 || { echo "Compile failed $i"; exit; }
+    sed -e 's/;/:/g' -e 's/\\/\//g' run.bat | bash 2>&1 || echo "Run failed $i"
     echo 
 )
 done
